package com.myspace.invoicecancellation;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SampleRequest implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public SampleRequest() {
    }




}